### ISSUE TITLE
Use isinstance() to check if data is already a dataframe

### ISSUE THREAD

**Issue by Shotgunosine** [nimh-mbdu/data-reliability-stability#3]
https://github.com/nimh-mbdu/data-reliability-stability/blob/27ad1fbc825354dd0e8bd17819b6b074b04a44e3/reliability_stability_pkg/reliability_stability.py#L6-L16

In your correlation wrapper function, you might be able to make it a bit faster if you use `isinstance` to check if data is already a DataFrame, then you wouldn't have to convert it.

**Comment by lilyeisner** [comment]
Got rid of DataFrame conversion in correlation calculation wrapper
